[package]
name = "chapter-07-listing-10"
version = "0.1.0"
edition = "2018"

[lib]
name = "rust_json"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
pyo3 = { version = "0.14", features = ["extension-module"] }
