[package]
name = "chapter-04-listing-14"
version = "0.1.0"
authors = ["You <you@you.com>"]
edition = "2018"
# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
libc = "0.2.80"
