[package]
name = "chapter-06-listing-00"
version = "0.1.0"
edition = "2018"

[lib]
name = "json_summer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.14", features = ["extension-module"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
