[package]
name = "chapter-03-listing-04"
version = "0.1.0"
authors = ["You <you@you.com>"]
edition = "2018"
# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.80"
